spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
